config/routes.rb
Rails.application.routes.draw do
  get "/javascript/audios/_sound_incorrect1.mp3"=>"controller_name#action_name"
  get "/javascript/audios/_sound_correct.mp3"=>"controller_name#action_name"

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post "users/guest_sign_in"=>"public/sessions#guest_sign_in"
    get "users/guest_sign_in"=>"public/sessions#guest_sign_in"
    delete "users/guest_sign_out"=>"public/sessions#destroy"
  end

  scope module: :public do
    root to: "homes#top"
    post "posts/:id/comments/:id/favorites/:id"=>"favorites#create", as: :post_comment_favorites
    delete "posts/:id/comments/:id/favorites/:id"=>"favorites#destroy", as: :post_comment_favorite
    get "search"=>"searches#search"
    get "typing"=>"typings#index"

    resources :users, only: [:show, :edit, :update] do
      member do
        get :liked_comments
      end
    end
    resources :scoreboards, only: [:index, :create]
    resources :contacts, only: [:new, :create]
    resources :typings, only: [:index]
    resources :posts, only: [:index, :new, :create, :show] do
      resources :comments, only: [:create, :destroy, :edit, :update] do
        resources :favorites, only: [:create, :destroy]
      end
    end
  end

  namespace :admin do
    get "/"=>"homes#top"
    get "admins/sign_out"=>"admin/sessions#destroy"
    get '/search', to: 'searches#search', as: :admin_search
    resources :users, only: [:index, :show, :edit, :update] do
      member do
        patch :withdraw
      end
    end
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: [:index, :destroy]
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_many :favorites, dependent: :destroy
  belongs_to :user
  belongs_to :post

  validates :content, presence: true

  #いいね数を計算するメソッド
  def favorited_by?(user)
    return false unless user
    favorites.exists?(user_id: user.id)
  end

  #いいねしたコメントを表示
  def self.liked_comments(user, page, per_page)
  includes(:favorites)
    .where(favorites: { user_id: user.id })
    .order(created_at: :desc)
    .page(page)
    .per(per_page)
  end

  #検索機能
  def self.looks(search, word)
    if search == "perfect_match"
      @comment = Comment.where("content LIKE?", "#{word}")
    elsif search == "forward_match"
      @comment = Comment.where("content LIKE?","#{word}%")
    elsif search == "backward_match"
      @comment = Comment.where("content LIKE?","%#{word}")
    elsif search == "partical_match"
      @comment = Comment.where("content LIKE?","%#{word}%")
    else
      @comment = Comment.all
    end
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :content, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :comment
  #belongs_to :post

  validates :user_id, uniqueness: {scope: :comment_id} #一人のユーザーが一つのコメントに複数いいねを押せないようにする機能
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  #has_many :favorites, dependent: :destroy
  belongs_to :user

  validates :title, presence:  { message: "を入力してください" }
  validates :content, presence: { message: "を入力してください" }

  #コメント数を計算するメソッド
  def update_comment_count
    update(comment_count: comments.count)
  end

  #ユーザーのアイコン表示機能
  has_one_attached :image

  #検索機能
  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("title LIKE?", "#{word}")
    elsif search == "forward_match"
      @post = Post.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @post = Post.where("title LIKE?","%#{word}")
    elsif search == "partical_match"
      @post = Post.where("title LIKE?","%#{word}%")
    else
      @post = Post.all
    end
  end
end

app/models/scoreboard.rb
class Scoreboard < ApplicationRecord
  belongs_to :user

  validates :ranking, presence: true
end

app/models/typing.rb
class Typing < ApplicationRecord
  #has_many: :scoreboards, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :typings, dependent: :destroy
  has_many :scoreboards, dependent: :destroy

  scope :latest, -> { order(created_at: :desc) }


  GUEST_USER_EMAIL = "guest@guest.com"

  #ゲストログイン機能
  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.handle = "ゲスト"
    end
  end

  #ゲストログアウト機能
  def guest?
    email == GUEST_USER_EMAIL
  end

  #ユーザーのアイコン表示機能
  has_one_attached :image

  #いいねしたコメントを表示
  def self.liked_comments(user, page, per_page)
  includes(:favorites)
    .where(favorites: { user_id: user.id })
    .order(created_at: :desc)
    .page(page)
    .per(per_page)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top
  end
  
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @posts = Post.all
    @user = current_user
  end

  def show
    @post = Post.find(params[:id])
    @posts = Post.all
    @user = @post.user
    @comment = Comment.new
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end
end

app/controllers/admin/typings_controller.rb
class Admin::TypingsController < ApplicationController
  before_action :authenticate_admin!
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.latest
  end

  def show
    @user = User.find(params[:id])
  end

  #退会アクション
  def withdraw
    @user = User.find(params[:id])
    @user.update(is_active: !@user.is_active)
    reset_session
    redirect_to admin_users_path, notice: 'ユーザーのステータスを変更しました。'
  end

  #画像変更アクション
  def edit
    @user = User.find(params[:id])
  end

  #画像更新アクション
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_user_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #layout :layout_by_resource

  #private

  #def layout_by_resource
    #if request.path.include?('admin')
      #'admin_layout'
    #else
      #'user_layout'
    #end
  #end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/favorites_helper.rb
module Admin::FavoritesHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/scoreboards_helper.rb
module Admin::ScoreboardsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/typings_helper.rb
module Admin::TypingsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/posts/index.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="card">
        <div class="card-header bg-dark text-white">
          <h4 class="mb-0">掲示板一覧</h4>
        </div>
        <div class="card-body">
          <% @posts.each do |post| %>
            <div class="card mb-3">
              <div class="card-body">
                <%= link_to admin_post_path(post) do %>
                  <h5 class="card-title">【<%= post.id %>】 <%= post.title %></h5>
                <% end %>
                <p class="card-text">投稿者: <%= post.user.handle %></p>
                <p class="card-text">コメント数: <%= post.comments.count %></p>
                <%= link_to "削除", admin_post_path(post), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="card">
        <div class="card-header bg-dark text-white">
          <h4 class="mb-0"><%= @post.title %></h4>
        </div>
        <div class="card-body">
          <% if @post.user && @post.user.image.attached? %>
            <%= image_tag @post.user.image, size: "100x100", class: "mr-3 rounded-circle" %>
          <% else %>
            <%= image_tag 'sennin', size: "100x100", class: "mr-3 rounded-circle" %>
          <% end %>
          <p class="card-text">投稿者: <%= link_to @post.user.handle, admin_user_path(@post.user) %></p>
          <p class="card-text"><%= @post.content %></p>
          <p class="card-text">投稿日：<%= @post.created_at.strftime("%Y-%m-%d %H:%M:%S") %></p>
        </div>
      </div>
      <div class="card mt-4">
        <div class="card-header bg-dark text-white">
          <h5 class="mb-0">コメント件数：<%= @post.comments.count %></h5>
        </div>
        <div class="card-body">
          <% @post.comments.each do |comment| %>
            <div class="media mb-4">
              <% if comment.user && comment.user.image.attached? %>
                <%= image_tag comment.user.image, size: "100x100", class: "mr-3 rounded-circle" %>
              <% else %>
                <%= image_tag 'sennin', size: "100x100", class: "mr-3 rounded-circle" %>
              <% end %>
              <div class="media-body">
                <h6 class="mt-0"><strong><%= link_to comment.user.handle, admin_user_path(comment.user) %></strong></h6>
                <p><small><%= comment.created_at.strftime('%Y/%m/%d') %></small></p>
                <p><%= comment.content %></p>
                  <%= link_to "削除", admin_post_comment_path(@post, comment), method: :delete, class: "btn btn-danger btn-sm" %>
                <p><%= render "layouts/btn", comment: comment %></p>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/edit.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title text-center mb-4">ユーザーのプロフィール編集</h2>
          <%= form_with model: @user, url: admin_user_path(@user), method: :patch do |f| %>
            <div class="mb-3">
              <%= f.label :handle, "ハンドルネーム" %>
              <%= f.text_field :handle, class: "form-control", autofocus: true, autocomplete: "handle" %>
            </div>
            <div class="mb-3">
              <h4>画像</h4>
              <%= f.file_field :image, accept: "image/*", class: "form-control" %>
            </div>
            <%= f.submit "編集内容を保存", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container mb-4">
  <div class="row justify-content-center">
    <div class="col-12">
      <h1 class="text-center display-4 font-weight-bold mb-4">Users</h1>
    </div>
    <div class="col-12">
      <div class="card rounded-3xl border-0">
        <div class="card-body p-0">
          <div class="table-responsive">
            <table class="table table-bordered mb-0">
              <thead>
                <tr>
                  <th class="px-6 py-3 font-weight-bold text-left text-uppercase border-0">Handle</th>
                  <th class="px-6 py-3 font-weight-bold text-left text-uppercase border-0">Email</th>
                  <th class="px-6 py-3 font-weight-bold text-center text-uppercase border-0">Status</th>
                  <th class="px-6 py-3 font-weight-bold text-left text-uppercase border-0">Ban/Unban</th>
                  <th class="px-6 py-3 font-weight-bold text-left text-uppercase border-0">Profile</th>
                  <th class="px-6 py-3 font-weight-semibold text-capitalize border-0"></th>
                </tr>
              </thead>
              <tbody>
                <% @users.each do |user| %>
                  <tr>
                    <td class="p-2 align-middle"><%= user.handle %></td>
                    <td class="p-2 align-middle"><%= user.email %></td>
                    <td class="p-2 text-center align-middle">
                      <% if user.is_active %>
                        <span class="badge bg-primary text-white">Normal</span>
                      <% else %>
                        <span class="badge bg-danger text-white">Banned</span>
                      <% end %>
                    </td>
                    <td class="p-2 align-middle">
                      <% if user.is_active %>
                        <%= link_to "退会する", withdraw_admin_user_path(user), method: :patch, class: "text-muted", data: { confirm: '本当に退会させますか？' } %>
                      <% else %>
                        <%= link_to "再開する", withdraw_admin_user_path(user), method: :patch, class: "text-muted", data: { confirm: '本当に再開させますか？' } %>
                      <% end %>
                    </td>
                    <td class="p-2 align-middle">
                      <%= link_to admin_user_path(user), class: "text-muted" do %>
                        詳細
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body text-center">
          <h3 class="text-dark"><%= @user.handle %></h3>
          <% if @user.image.attached? %>
            <%= image_tag @user.image, size: "125x125", class: "profile-image img-fluid rounded-circle mb-3" %>
          <% else %>
            <%= image_tag 'sennin', size: "125x125", class: "profile-image img-fluid rounded-circle mb-3" %>
          <% end %>
          <%#= link_to "プロフィールを強制変更する", edit_admin_user_path, class: "btn btn-outline-dark" %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card bg-light p-3">
        <div class="card-body">
          <h4 class="card-title">コメント一覧</h4>
          <% @user.comments.each do |comment| %>
            <div class="media mb-3 bg-light p-3">
              <div class="media-body">
                <h5 class="mt-0">スレッド名: <%= link_to comment.post.title, admin_post_path(comment.post) %></h5>
                <p>コメント内容: <%= comment.content %></p>
                <small><%= comment.created_at.strftime('%Y-%m-%d %H:%M:%S') %></small>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>