config/routes.rb
Rails.application.routes.draw do
  get "/javascript/audios/_sound_incorrect1.mp3"=>"controller_name#action_name"
  get "/javascript/audios/_sound_correct.mp3"=>"controller_name#action_name"

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post "users/guest_sign_in"=>"public/sessions#guest_sign_in"
    get "users/guest_sign_in"=>"public/sessions#guest_sign_in"
    delete "users/guest_sign_out"=>"public/sessions#destroy"
  end

  scope module: :public do
    root to: "homes#top"
    post "posts/:id/comments/:id/favorites/:id"=>"favorites#create", as: :post_comment_favorites
    delete "posts/:id/comments/:id/favorites/:id"=>"favorites#destroy", as: :post_comment_favorite
    get "search"=>"searches#search"
    get "typing"=>"typings#index"

    resources :users, only: [:show, :edit, :update] do
      member do
        get :liked_comments
      end
    end
    resources :scoreboards, only: [:index, :create]
    resources :contacts, only: [:new, :create]
    resources :typings, only: [:index]
    resources :posts, only: [:index, :new, :create, :show] do
      resources :comments, only: [:create, :destroy, :edit, :update] do
        resources :favorites, only: [:create, :destroy]
      end
    end
  end

  namespace :admin do
    get "/"=>"homes#top"
    get "admins/sign_out"=>"admin/sessions#destroy"
    get '/search', to: 'searches#search', as: :admin_search
    resources :users, only: [:index, :show, :edit, :update] do
      member do
        patch :withdraw
      end
    end
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: [:index, :destroy]
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_many :favorites, dependent: :destroy
  belongs_to :user
  belongs_to :post

  validates :content, presence: true

  #いいね数を計算するメソッド
  def favorited_by?(user)
    return false unless user
    favorites.exists?(user_id: user.id)
  end

  #いいねしたコメントを表示
  def self.liked_comments(user, page, per_page)
  includes(:favorites)
    .where(favorites: { user_id: user.id })
    .order(created_at: :desc)
    .page(page)
    .per(per_page)
  end

  #検索機能
  def self.looks(search, word)
    if search == "perfect_match"
      @comment = Comment.where("content LIKE?", "#{word}")
    elsif search == "forward_match"
      @comment = Comment.where("content LIKE?","#{word}%")
    elsif search == "backward_match"
      @comment = Comment.where("content LIKE?","%#{word}")
    elsif search == "partical_match"
      @comment = Comment.where("content LIKE?","%#{word}%")
    else
      @comment = Comment.all
    end
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :content, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :comment
  #belongs_to :post

  validates :user_id, uniqueness: {scope: :comment_id} #一人のユーザーが一つのコメントに複数いいねを押せないようにする機能
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  #has_many :favorites, dependent: :destroy
  belongs_to :user

  validates :title, presence:  { message: "を入力してください" }
  validates :content, presence: { message: "を入力してください" }

  #コメント数を計算するメソッド
  def update_comment_count
    update(comment_count: comments.count)
  end

  #ユーザーのアイコン表示機能
  has_one_attached :image

  #検索機能
  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("title LIKE?", "#{word}")
    elsif search == "forward_match"
      @post = Post.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @post = Post.where("title LIKE?","%#{word}")
    elsif search == "partical_match"
      @post = Post.where("title LIKE?","%#{word}%")
    else
      @post = Post.all
    end
  end
end

app/models/scoreboard.rb
class Scoreboard < ApplicationRecord
  belongs_to :user

  validates :ranking, presence: true
end

app/models/typing.rb
class Typing < ApplicationRecord
  #has_many: :scoreboards, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :typings, dependent: :destroy
  has_many :scoreboards, dependent: :destroy

  scope :latest, -> { order(created_at: :desc) }


  GUEST_USER_EMAIL = "guest@guest.com"

  #ゲストログイン機能
  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.handle = "ゲスト"
    end
  end

  #ゲストログアウト機能
  def guest?
    email == GUEST_USER_EMAIL
  end

  #ユーザーのアイコン表示機能
  has_one_attached :image

  #いいねしたコメントを表示
  def self.liked_comments(user, page, per_page)
  includes(:favorites)
    .where(favorites: { user_id: user.id })
    .order(created_at: :desc)
    .page(page)
    .per(per_page)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #layout :layout_by_resource

  #private

  #def layout_by_resource
    #if request.path.include?('admin')
      #'admin_layout'
    #else
      #'user_layout'
    #end
  #end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/favorites_helper.rb
module Admin::FavoritesHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/scoreboards_helper.rb
module Admin::ScoreboardsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/typings_helper.rb
module Admin::TypingsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_btn.html.erb
<% if user_signed_in? %>
  <% if comment.favorited_by?(current_user) %>
    <%= link_to post_comment_favorite_path(post_id: comment.post.id, comment_id: comment.id), method: :delete do %>
      <i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
      ❤<%= comment.favorites.count %> いいね
    <% end %>
  <% else %>
    <%= link_to post_comment_favorites_path(post_id: comment.post.id, comment_id: comment.id), method: :post do %>
      <i class="fas fa-heart" aria-hidden="true"></i>
      ❤<%= comment.favorites.count %> いいね
    <% end %>
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <div class="p-1 border-bottom border-secondary">
    <nav class="container">
      <div class="row align-items-center">
        <div class="col">
          <% if admin_signed_in? %>
            <%= link_to "タイピング仙人", admin_path, class: "custom-link" %>
          <% else %>
            <%= link_to "タイピング仙人", root_path, class: "custom-link"  %>
          <% end %>
        </div>
        <div class="col text-right">
          <% if admin_signed_in? %>
            <div class="search_form">
              <%= form_with url: admin_admin_search_path, local: true, method: :get, class: "d-flex align-items-center" do |f| %>
                <%= f.text_field :word, class: "form-control mr-2", placeholder: "検索" %>
                <%= f.select :range, options_for_select([['コメント'], ['タイトル']]), {}, class: "form-control mr-2" %>
                <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"], ["後方一致","backward_match"], ["部分一致","partial_match"]]), {}, class: "form-control mr-2" %>
                <%= f.submit "検索", class: "btn btn-primary" %>
              <% end %>
            </div>
            <ul class="list-inline">
              <li class="list-inline-item">
                <%= link_to "ユーザー一覧", admin_users_path, class: "btn btn-outline-dark" %>
              </li>
              <li class="list-inline-item">
                <%= link_to "スレッド一覧", admin_posts_path, class: "btn btn-outline-dark" %>
              </li>
              <li class="list-inline-item">
                <%= link_to "ログアウト", destroy_admin_session_path, class: "btn btn-outline-dark", data: { turbo_method: :delete } %>
              </li>
            </ul>
          <% else %>
            <div class="search_form">
              <%= form_with url: search_path, local: true, method: :get, class: "d-flex align-items-center" do |f| %>
                <%= f.text_field :word, class: "form-control mr-2", placeholder: "検索" %>
                <%= f.select :range, options_for_select([['コメント'], ['タイトル']]), {}, class: "form-control mr-2" %>
                <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"], ["後方一致","backward_match"], ["部分一致","partial_match"]]), {}, class: "form-control mr-2" %>
                <%= f.submit "検索", class: "btn btn-primary" %>
              <% end %>
            </div>
            <ul class="list-inline">
              <% if !user_signed_in? && !current_user&.guest? %>
                <li class="list-inline-item">
                  <%= link_to "ゲストログイン", users_guest_sign_in_path, class: "btn btn-outline-dark" %>
                </li>
              <% end %>
              <li class="list-inline-item">
                <%= link_to "タイピング", typing_path, class: "btn btn-outline-dark" %>
              </li>
              <li class="list-inline-item">
                <%= link_to "お喋り広場", posts_path, class: "btn btn-outline-dark" %>
              </li>
              <li class="list-inline-item">
                <%= link_to "お問い合わせ", new_contact_path, class: "btn btn-outline-dark" %>
              </li>
              <% if user_signed_in? %>
                <li class="list-inline-item">
                  <%= link_to "プロフィール", user_path(current_user), class: "btn btn-outline-dark" %>
                </li>
                <li class="list-inline-item">
                  <%= link_to "ログアウト", destroy_user_session_path, class: "btn btn-outline-dark", data: { turbo_method: :delete } %>
                </li>
              <% else %>
                <li class="list-inline-item">
                  <%= link_to "新規登録", new_user_registration_path, class: "btn btn-outline-dark" %>
                </li>
                <li class="list-inline-item">
                  <%= link_to "ログイン", new_user_session_path, class: "btn btn-outline-dark" %>
                </li>
              <% end %>
            </ul>
          <% end %>
        </div>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/_user_header.html.erb
<header>
  <div class="p-1 border-bottom border-secondary">
    <nav class="container">
      <div class="row align-items-center">
        <div class="col">
          <% if admin_signed_in? %>
            <%= link_to admin_path do %>
              <%= image_tag("typing_sennin", alt: "LOGO", size: "100x50") %>
            <% end %>
          <% else %>
            <%= link_to root_path do %>
              <%= image_tag("typing_sennin", alt: "LOGO", size: "100x50") %>
            <% end %>
          <% end %>
        </div>
        <div class="col text-right">
          <% if admin_signed_in? %>
            <div class="search_form">
              <%= form_with url: admin_admin_search_path, local: true, method: :get, class: "d-flex align-items-center" do |f| %>
                <%= f.text_field :word, class: "form-control mr-2", placeholder: "検索" %>
                <%= f.select :range, options_for_select([['コメント'], ['タイトル']]), {}, class: "form-control mr-2" %>
                <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"], ["後方一致","backward_match"], ["部分一致","partial_match"]]), {}, class: "form-control mr-2" %>
                <%= f.submit "検索", class: "btn btn-primary" %>
              <% end %>
            </div>
            <ul class="list-inline">
              <li class="list-inline-item">
                <%= link_to "ユーザー一覧", admin_users_path, class: "btn btn-outline-dark" %>
              </li>
              <li class="list-inline-item">
                <%= link_to "スレッド一覧", admin_posts_path, class: "btn btn-outline-dark" %>
              </li>
              <li class="list-inline-item">
                <%= link_to "ログアウト", destroy_admin_session_path, class: "btn btn-outline-dark", data: { turbo_method: :delete } %>
              </li>
            </ul>
          <% else %>
            <div class="search_form">
              <%= form_with url: search_path, local: true, method: :get, class: "d-flex align-items-center" do |f| %>
                <%= f.text_field :word, class: "form-control mr-2", placeholder: "検索" %>
                <%= f.select :range, options_for_select([['コメント'], ['タイトル']]), {}, class: "form-control mr-2" %>
                <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"], ["後方一致","backward_match"], ["部分一致","partial_match"]]), {}, class: "form-control mr-2" %>
                <%= f.submit "検索", class: "btn btn-primary" %>
              <% end %>
            </div>
            <ul class="list-inline">
              <% if !user_signed_in? && !current_user&.guest? %>
                <li class="list-inline-item">
                  <%= link_to "ゲストログイン", users_guest_sign_in_path, class: "btn btn-outline-dark" %>
                </li>
              <% end %>
              <li class="list-inline-item">
                <%= link_to "タイピング", typing_path, class: "btn btn-outline-dark" %>
              </li>
              <li class="list-inline-item">
                <%= link_to "お喋り広場", posts_path, class: "btn btn-outline-dark" %>
              </li>
              <li class="list-inline-item">
                <%= link_to "お問い合わせ", new_contact_path, class: "btn btn-outline-dark" %>
              </li>
              <% if user_signed_in? %>
                <li class="list-inline-item">
                  <%= link_to "プロフィール", user_path(current_user), class: "btn btn-outline-dark" %>
                </li>
                <li class="list-inline-item">
                  <%= link_to "ログアウト", destroy_user_session_path, class: "btn btn-outline-dark", data: { turbo_method: :delete } %>
                </li>
              <% else %>
                <li class="list-inline-item">
                  <%= link_to "新規登録", new_user_registration_path, class: "btn btn-outline-dark" %>
                </li>
                <li class="list-inline-item">
                  <%= link_to "ログイン", new_user_session_path, class: "btn btn-outline-dark" %>
                </li>
              <% end %>
            </ul>
          <% end %>
        </div>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render "layouts/header" %>
    </header>
    <div class="container">
      <% if notice %>
        <div class="alert alert-success" role="alert">
          <%= notice %>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger" role="alert">
          <%= alert %>
        </div>
      <% end %>
    <%= yield %>
  </body>
</html>